export interface IBMO {
customerName:string,
customerNumber: string,
CustomerNumber:string,
customerType: string,
kycReferenceNumber: string,
level: string,
rating: number,
rcNumber: string,
RcNumber:string,
riskLevel: string,
}

export interface IParent {
    AuthorizeBy: string,
    AuthorizeDate: string,
    BVN: string,
    BusinessName: string,
    Category: string,
    CategoryDescription: string,
    Comments: string,
    CountryId: string,
    CountryName: string,
    CreatedBy: string,
    CreatedDate: string,
    CustomerNumber: string,
    Id: string,
    IdNumber: string,
    IdType: string,
    IsAuthorized: boolean,
    IsPEP: boolean,
    IsRejected: boolean,
    LastUpdatedBy: null,
    LastUpdatedDate: null,
    Level: number,
    NumberOfShares: number,
    ParentId: null,
    PercentageHolding: number,
    RcNumber: string,
    RejectedBy: string,
    RejectedDate: null,
    RiskLevel: null,
    RiskScore: null,
    Ticker: string
}


export interface IOwner{
serialNumber:number,
AuthorizeBy: string,
AuthorizeDate:null
BVN:string,
BusinessName: string,
Category: string,
CategoryDescription: string,
Comments: string,
CountryId: string,
CountryName:null
CreatedBy: string,
CreatedDate: string,
CustomerNumber: string,
Id: number,
IdNumber: string,
IdType: string,
IsAuthorized:boolean,
IsPEP:boolean,
IsRejected:boolean,
Level:number,
NumberOfShares:number,
ParentId:number,
PercentageHolding:number,
RcNumber: string,
RejectedBy: string,
RejectedDate: null,
RiskLevel:null,
RiskScore:null,
Ticker: string,
ownerId:any
}